steps:
  # Stage Trade Predictor Cloud Function source
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'stage-predictor-function-source'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf ./gcf_src_predictor
        mkdir -p ./gcf_src_predictor
        cp cloud_function/trade_predictor/app/main.py ./gcf_src_predictor/main.py
        cp cloud_function/trade_predictor/requirements.txt ./gcf_src_predictor/requirements.txt
        # Copy any model files if they exist
        if [ -d models ]; then
          cp -R models ./gcf_src_predictor/
        fi

  # Create VM service account if it doesn't exist
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-vm-service-account'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud iam service-accounts describe "${_VM_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com" >/dev/null 2>&1; then
          gcloud iam service-accounts create "${_VM_SERVICE_ACCOUNT}" \
            --display-name="Delta Bot VM Service Account"
        fi

  # Deploy Trade Predictor Cloud Function (Gen2, authenticated only)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-trade-predictor'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy "${_PREDICTOR_FUNCTION_NAME}" \
          --gen2 \
          --region "${_CLOUD_FUNCTION_REGION}" \
          --runtime python312 \
          --source ./gcf_src_predictor \
          --entry-point predict_trade \
          --trigger-http \
          --no-allow-unauthenticated
        
        # Grant VM service account permission to invoke this function
        gcloud functions add-invoker-policy-binding "${_PREDICTOR_FUNCTION_NAME}" \
          --region "${_CLOUD_FUNCTION_REGION}" \
          --member "serviceAccount:${_VM_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com"
    waitFor: ['stage-predictor-function-source', 'create-vm-service-account']

  # Verify deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-predictor-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Trade Predictor function deployed successfully"
        gcloud functions describe "${_PREDICTOR_FUNCTION_NAME}" \
          --region "${_CLOUD_FUNCTION_REGION}" \
          --format 'table(name,status,serviceConfig.uri)'
    waitFor: ['deploy-trade-predictor']

substitutions:
  _PREDICTOR_FUNCTION_NAME: 'trade-predictor'
  _CLOUD_FUNCTION_REGION: 'us-central1'
  _VM_SERVICE_ACCOUNT: 'delta-bot-vm'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
